### ISSUE TITLE
No joy with Version 3.0.1 (7597) 

### ISSUE THREAD

**Issue by VincentStephens** [dunckr/sketch-subtlepatterns#1]
I have tried install via git clone, downloading the zip and finally using the Sketch Toolbox app: http://sketchtoolbox.com/

I get the plugin in the the menu with the random option but no patterns are rendered.  I have just noticed that no other plugins are working so this is not an issue specific to this repo. Any ideas how to get plugin functionality into sketch?  

Thanks

**Comment by dunckr** [comment]
Just checking but have you to selected a shape first before running the plugin?

Failing that, did you install via the app store or [dmg](http://bohemiancoding.com/sketch/store/)?

**Comment by achiandet** [comment]
Are you able to choose a specific pattern or do you have to use the random feature?

**Comment by dunckr** [comment]
@achiandet yes it is just random at the moment. Ideally you could see a list of preview images and be able to select one.

Unfortunately there isn't really a nice way to implement this easily in sketch. It would involve messing with native apis which aren't support from inside sketch.

The simple alternatives could be:
- Show a dialog dropdown like this:
  ![image](https://cloud.githubusercontent.com/assets/2514366/8684623/764fc7fe-2a71-11e5-8847-e73d5744592d.png)
- Separating each images into it's own sub-menus in the sketch-plugin.

Neither one would be that great to use IMO

**Comment by achiandet** [comment]
That's cool, I just wanted to make sure I wasn't missing something obvious.  Thanks!
