### ISSUE TITLE
Syntax error on update script

### ISSUE THREAD

**Issue by gldtn** [dunckr/sketch-subtlepatterns#5]
When I ran ./update.sh everything went fine until it tried to remove images..

`./update.sh: line 7: syntax error near unexpected token`('
./update.sh: line 7: `rm SubtlePatterns/!(*.png|*.jpg)'`

`7. rm SubtlePatterns/!(*.png|*.jpg)`

I'm running OSX 10.11.5, tried running on my iterm2 console

**Comment by dunckr** [comment]
Thanks for letting me know. I think this is advanced pattern matching. I have updated.
