### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [dunckr/sketch-subtlepatterns#6]
Hi there,

As you probably know, `setPatternImage:` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `setImage:` instead or it won't work in the next release :)

**Comment by dunckr** [comment]
Thanks for the heads up @bomberstudios!

**Comment by dunckr** [comment]
I've just double checked this and I think it's covered by this version [check](https://github.com/dunckr/sketch-utils/blob/master/index.js#L34).

If I'm mistaken I'll correct. Cheers!
